/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ResumesIndexImport } from './routes/resumes.index'
import { Route as ResumesResumeIdIndexImport } from './routes/resumes.$resumeId.index'
import { Route as ResumesResumeIdEditImport } from './routes/resumes.$resumeId.edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResumesIndexRoute = ResumesIndexImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRoute,
} as any)

const ResumesResumeIdIndexRoute = ResumesResumeIdIndexImport.update({
  id: '/resumes/$resumeId/',
  path: '/resumes/$resumeId/',
  getParentRoute: () => rootRoute,
} as any)

const ResumesResumeIdEditRoute = ResumesResumeIdEditImport.update({
  id: '/resumes/$resumeId/edit',
  path: '/resumes/$resumeId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesIndexImport
      parentRoute: typeof rootRoute
    }
    '/resumes/$resumeId/edit': {
      id: '/resumes/$resumeId/edit'
      path: '/resumes/$resumeId/edit'
      fullPath: '/resumes/$resumeId/edit'
      preLoaderRoute: typeof ResumesResumeIdEditImport
      parentRoute: typeof rootRoute
    }
    '/resumes/$resumeId/': {
      id: '/resumes/$resumeId/'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/resumes/$resumeId/edit': typeof ResumesResumeIdEditRoute
  '/resumes/$resumeId': typeof ResumesResumeIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/resumes/$resumeId/edit': typeof ResumesResumeIdEditRoute
  '/resumes/$resumeId': typeof ResumesResumeIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/resumes/$resumeId/edit': typeof ResumesResumeIdEditRoute
  '/resumes/$resumeId/': typeof ResumesResumeIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resumes' | '/resumes/$resumeId/edit' | '/resumes/$resumeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resumes' | '/resumes/$resumeId/edit' | '/resumes/$resumeId'
  id:
    | '__root__'
    | '/'
    | '/resumes/'
    | '/resumes/$resumeId/edit'
    | '/resumes/$resumeId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  ResumesResumeIdEditRoute: typeof ResumesResumeIdEditRoute
  ResumesResumeIdIndexRoute: typeof ResumesResumeIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  ResumesResumeIdEditRoute: ResumesResumeIdEditRoute,
  ResumesResumeIdIndexRoute: ResumesResumeIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/resumes/",
        "/resumes/$resumeId/edit",
        "/resumes/$resumeId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/resumes/": {
      "filePath": "resumes.index.tsx"
    },
    "/resumes/$resumeId/edit": {
      "filePath": "resumes.$resumeId.edit.tsx"
    },
    "/resumes/$resumeId/": {
      "filePath": "resumes.$resumeId.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
